### ISSUE TITLE
Failed to build locally

### ISSUE THREAD

**Issue by jonatas** [timescale/opentelemetry-demo#3]
Hello! I'm trying to build it locally with `./run.sh` and I got the following error:

```
=> ERROR [internal] load metadata for docker.io/otel/opentelemetry-collector:0.42.0       0.9s
------
 > [internal] load metadata for docker.io/otel/opentelemetry-collector:0.42.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:cecb0904bcc2a90c823c2c044e7034934ab6c98b5ec52c337c0f6c6e57cd3cf1: not found
ERROR: Service 'collector' failed to build : Build failed
```

I see [a similar question here](https://stackoverflow.com/questions/68984133/error-failed-to-solve-with-frontend-dockerfile-v0-failed-to-create-llb-definit) maybe the images was build to another system?

I'm on MacOs Monterey 12.1.

**Comment by jgpruitt** [comment]
@jonatas is your mac intel or an M1?

**Comment by jgpruitt** [comment]
looks like 0.42.0 is only built for intel
![image](https://user-images.githubusercontent.com/4974668/151584449-a8b420dc-b038-4427-865d-fb0daffe60f5.png)

but 0.43.0 is built for intel AND arm
![image](https://user-images.githubusercontent.com/4974668/151584593-d1287771-e29a-42cf-ac06-46f279b60b94.png)
