### ISSUE TITLE
Make the OTLP endpoint the services write to configurable

### ISSUE THREAD

**Issue by ramonguiu** [timescale/opentelemetry-demo#6]
Currently the OTLP endpoint used by the Python services is hardcoded:
`OTLPSpanExporter(endpoint="collector:4317")`

Can we make it configurable via environment variables? The Python SDK already has [support](https://opentelemetry-python.readthedocs.io/en/latest/sdk/environment_variables.html#envvar-OTEL_EXPORTER_OTLP_ENDPOINT) for that.

It seems to be the same in Ruby: https://open-telemetry.github.io/opentelemetry-ruby/opentelemetry-exporter-otlp/v0.20.3/
The lower service is already leveraging that same variable.

**Comment by jgpruitt** [comment]
addressed in https://github.com/timescale/opentelemetry-demo/commit/df07815493b42166153aa2279e629909e54db6f4
