### ISSUE TITLE
Add support for Mac M1

### ISSUE THREAD

**Issue by ramonguiu** [timescale/opentelemetry-demo#7]
The TimescaleDB image used in the demo is not provided for ARM architectures and so the demo will not work on M1-based Mac computers.

**Comment by jgpruitt** [comment]
@ramonguiu we need a docker image that includes the timescaledb-toolkit and ideally the promscale extensions for the ARM architectures.

**Comment by ramonguiu** [comment]
I think I ended up testing this and it actually worked. I think the performance may not be great though since it uses emulation to run x86 on top of ARM.

**Comment by jonatas** [comment]
The [HA](https://github.com/timescale/opentelemetry-demo/blob/main/instrumented/timescaledb/Dockerfile#L1) version actually includes it. Closing the issue as it seems working now. At least I'm running it on my M1 too.
